#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[ANTDIV]
// [ANTDIV]$

// $[BATTERYMON]
// [BATTERYMON]$

// $[BTL_BUTTON]
#define HAL_BTL_BUTTON_ENABLE                (1)

#define BSP_BTL_BUTTON_PIN                   (4U)
#define BSP_BTL_BUTTON_PORT                  (gpioPortF)

// [BTL_BUTTON]$

// $[BULBPWM]
// [BULBPWM]$

// $[BULBPWM_COLOR]
// [BULBPWM_COLOR]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                 (HAL_CLK_HFCLK_SOURCE_HFRCO)
#define HAL_CLK_LFECLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_LFBCLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define BSP_CLK_LFXO_PRESENT                 (1)
#define BSP_CLK_HFXO_PRESENT                 (1)
#define BSP_CLK_LFXO_INIT                     CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_CTUNE                   (32U)
#define BSP_CLK_LFXO_FREQ                    (32768U)
#define HAL_CLK_LFACLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define BSP_CLK_HFXO_FREQ                    (38400000UL)
#define BSP_CLK_HFXO_CTUNE                   (291)
#define BSP_CLK_HFXO_INIT                     CMU_HFXOINIT_DEFAULT
#define BSP_CLK_HFXO_CTUNE_TOKEN             (0)
#define HAL_CLK_HFXO_AUTOSTART               (HAL_CLK_HFXO_AUTOSTART_NONE)
// [CMU]$

// $[COEX]
// [COEX]$

// $[CS5463]
// [CS5463]$

// $[CSEN]
// [CSEN]$

// $[DCDC]
#define BSP_DCDC_PRESENT                     (1)

#define HAL_DCDC_BYPASS                      (0)
#define BSP_DCDC_INIT                         EMU_DCDCINIT_DEFAULT
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[FEM]
// [FEM]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[PA]
// [PA]$

// $[PCNT0]
// [PCNT0]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
// [PTI]$

// $[PYD1698]
// [PYD1698]$

// $[SERIAL]
#define BSP_SERIAL_APP_PORT                  (HAL_SERIAL_PORT_USART0)
#define BSP_SERIAL_APP_CTS_PIN               (2U)
#define BSP_SERIAL_APP_CTS_PORT              (gpioPortA)
#define BSP_SERIAL_APP_CTS_LOC               (30U)

#define BSP_SERIAL_APP_RX_PIN                (1U)
#define BSP_SERIAL_APP_RX_PORT               (gpioPortA)
#define BSP_SERIAL_APP_RX_LOC                (0U)

#define BSP_SERIAL_APP_TX_PIN                (0U)
#define BSP_SERIAL_APP_TX_PORT               (gpioPortA)
#define BSP_SERIAL_APP_TX_LOC                (0U)

#define BSP_SERIAL_APP_RTS_PIN               (3U)
#define BSP_SERIAL_APP_RTS_PORT              (gpioPortA)
#define BSP_SERIAL_APP_RTS_LOC               (30U)

#define HAL_SERIAL_APP_BAUD_RATE             (115200UL)
#define HAL_SERIAL_APP_FLOW_CONTROL          (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_CTS_PIN                (2U)
#define PORTIO_USART0_CTS_PORT               (gpioPortA)
#define PORTIO_USART0_CTS_LOC                (30U)

#define PORTIO_USART0_RTS_PIN                (3U)
#define PORTIO_USART0_RTS_PORT               (gpioPortA)
#define PORTIO_USART0_RTS_LOC                (30U)

#define PORTIO_USART0_RX_PIN                 (1U)
#define PORTIO_USART0_RX_PORT                (gpioPortA)
#define PORTIO_USART0_RX_LOC                 (0U)

#define PORTIO_USART0_TX_PIN                 (0U)
#define PORTIO_USART0_TX_PORT                (gpioPortA)
#define PORTIO_USART0_TX_LOC                 (0U)

#define HAL_USART0_ENABLE                    (1)

#define BSP_USART0_CTS_PIN                   (2U)
#define BSP_USART0_CTS_PORT                  (gpioPortA)
#define BSP_USART0_CTS_LOC                   (30U)

#define BSP_USART0_RX_PIN                    (1U)
#define BSP_USART0_RX_PORT                   (gpioPortA)
#define BSP_USART0_RX_LOC                    (0U)

#define BSP_USART0_TX_PIN                    (0U)
#define BSP_USART0_TX_PORT                   (gpioPortA)
#define BSP_USART0_TX_LOC                    (0U)

#define BSP_USART0_RTS_PIN                   (3U)
#define BSP_USART0_RTS_PORT                  (gpioPortA)
#define BSP_USART0_RTS_LOC                   (30U)

#define HAL_USART0_BAUD_RATE                 (115200UL)
#define HAL_USART0_FLOW_CONTROL              (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
// [USART1]$

// $[USART2]
// [USART2]$

// $[VCOM]
#define HAL_VCOM_ENABLE                      (1)

#define BSP_VCOM_ENABLE_PIN                  (5U)
#define BSP_VCOM_ENABLE_PORT                 (gpioPortA)

// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

#endif /* HAL_CONFIG_H */

