// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __SI_BOOTLOADER_CONFIG__
#define __SI_BOOTLOADER_CONFIG__


#define BTL_PLUGIN_STORAGE_NUM_SLOTS (1)

#define BTL_PLUGIN_STORAGE_SLOTS  \
  {\
    {278528, 241664}, /* Slot 0 */ \
  }\

// Number of slots in bootload list
#define BTL_STORAGE_BOOTLOAD_LIST_LENGTH BTL_PLUGIN_STORAGE_NUM_SLOTS


#endif // __SI_BOOTLOADER_CONFIG__
