platform :ios, '10.0'

workspace 'ble-mesh'

app_project = 'ble_mesh-app/ble_mesh-app.xcodeproj'
lib_project = 'BluetoothMesh/BluetoothMesh.xcodeproj'

project app_project
project lib_project

target 'ble_mesh-app' do
    use_frameworks!
    project app_project
    pod 'RxSwift', '4.1.2'
    pod 'RxCocoa', '4.1.2'
    pod 'SwiftyBeaver', '1.5.2'
    pod 'SWTableViewCell', '0.3.7'
    pod 'SVProgressHUD', '2.2.5'
end

target 'BluetoothMeshTests' do
    project lib_project
    pod 'Specta', '1.0.7'
    pod 'Expecta', '1.0.6'
    pod 'OCMock', '3.4.1'
end
