/*
 * zigbee_attributes.h: Zigbee cluster attirbutes and names.
 * Copyright (c) 2018
 *
 */
#ifndef __ZIGBEE_ATTRIBUTES_H__
#define __ZIGBEE_ATTRIBUTES_H__

#include "growhouse-server.h"

// Attributes object for reading.

typedef struct ZCLAttributeNames {

	int clusterId;
	int attributeId;
	char attribute_name[32];

} ZCLATTRIBUTENAME;

ZCLATTRIBUTENAME ZCLAttributeArray[] = {

	{ON_OFF_CLUSTER,-1,""},
	{COLOR_CONTROL_CLUSTER,-1,""},
	{LEVEL_CONTROL_CLUSTER,-1,""},

	{BOOTLOADER_CLUSTER,-1,""},
	{BOOTLOADER_CLUSTER,FIRMWARE_VERSION_ATTRIBUTE,"firmwareVersion"},
	{BOOTLOADER_CLUSTER,IMAGE_TYPE_ATTRIBUTE,"imageTypeId"},
	{BOOTLOADER_CLUSTER,MANUFACTURER_ID_ATTRIBUTE,"manufacturerId"},

	{IAS_ZONE_CLUSTER,-1,""},
	{IAS_ZONE_CLUSTER,ZONESTATUS_VAL_ATTRIBUTE,"zoneStatus"},

	{SIMPLE_METERING_CLUSTER,-1,""},
	{SIMPLE_METERING_CLUSTER,UNIT_OF_MEASURE_ATTRIBUTE,"powersumUnits"},
	{SIMPLE_METERING_CLUSTER,MULTIPLIER_ATTRIBUTE,"powersumMultiplier"},
	{SIMPLE_METERING_CLUSTER,DIVISOR_ATTRIBUTE,"powersumDivisor"},
	{SIMPLE_METERING_CLUSTER,SUMMATION_FORMATTING_ATTRIBUTE,"powersumFormatting"},
	{SIMPLE_METERING_CLUSTER,SUMMATION_VAL_ATTRIBUTE,"powersumValue"},

	{ILLUMINANCE_CLUSTER,-1,""},
	{ILLUMINANCE_CLUSTER,ILLUMINANCE_VAL_ATTRIBUTE,"luxReading"},

	{OCCUPANCY_CLUSTER,-1,""},
	{OCCUPANCY_CLUSTER,OCCUPANCY_VAL_ATTRIBUTE,"occupancyReading"},
	{OCCUPANCY_CLUSTER,OCCUPANCY_SENSOR_TYPE_ATTRIBUTE,"occupancySensorType"},

	{ELECTRICAL_CLUSTER,-1,""},
	{ELECTRICAL_CLUSTER,RMS_VOLTAGE_VAL_ATTRIBUTE,"rmsVoltage"},
	{ELECTRICAL_CLUSTER,RMS_CURRENT_VAL_ATTRIBUTE,"rmsCurrent"},
	{ELECTRICAL_CLUSTER,ACTIVE_POWER_VAL_ATTRIBUTE,"activePower"},
	{ELECTRICAL_CLUSTER,ALARMS_MASK_ATTRIBUTE,"alarmMask"},
	{ELECTRICAL_CLUSTER,VOLTAGE_OVERLOAD_ATTRIBUTE,"voltageOverload"},
	{ELECTRICAL_CLUSTER,CURRENT_OVERLOAD_ATTRIBUTE,"currentOverload"},
	{ELECTRICAL_CLUSTER,ACTIVE_POWER_OVERLOAD_ATTRIBUTE,"powerOverload"},

	{SOIL_NODE_PH_CLUSTER,-1,""},
	{SOIL_NODE_PH_CLUSTER,SOIL_NODE_PH_ATTRIBUTE,"soilPh"},
	{SOIL_NODE_MOISTURE_CLUSTER,-1,""},
	{SOIL_NODE_MOISTURE_CLUSTER,SOIL_NODE_MOISTURE_ATTRIBUTE,"soilMoisture"},

	{LIGHT_SHILED_CLUSTER,-1,""},
	{LIGHT_SHILED_CLUSTER,LIGHT_SHILED_R_ATTRIBUTE,"R"},
	{LIGHT_SHILED_CLUSTER,LIGHT_SHILED_G_ATTRIBUTE,"G"},
	{LIGHT_SHILED_CLUSTER,LIGHT_SHILED_B_ATTRIBUTE,"B"},

	{POWER_CONF_CLUSTER,-1,""},
	{POWER_CONF_CLUSTER,POWER_BATTERY_VOLTAGE_ATTRIBUTE, "batteryVoltage"},

	{SCM_TEMPERATURE_CLUSTER,-1,""},
	{SCM_TEMPERATURE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"temperature"},
	{SCM_PRESSURE_CLUSTER,-1,""},
	{SCM_PRESSURE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"pressure"},
	{SCM_HUMIDITY_CLUSTER,-1,""},
	{SCM_HUMIDITY_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"humidity"},
	{SCM_CARBON_MONOXIDE_CLUSTER,-1,""},
	{SCM_CARBON_MONOXIDE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"carbon_monoxide"},
	{SCM_CARBON_DIOXIDE_CLUSTER,-1,""},
	{SCM_CARBON_DIOXIDE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"carbon_dioxide"}
};

ZCLATTRIBUTENAME ReportableZCLAttributeArray[] = {

	{IAS_ZONE_CLUSTER,-1,""},
	{IAS_ZONE_CLUSTER,ZONESTATUS_VAL_ATTRIBUTE,"zoneStatus"},

	{SIMPLE_METERING_CLUSTER,-1,""},
	{SIMPLE_METERING_CLUSTER,SUMMATION_VAL_ATTRIBUTE,"powersumValue"},

	{ILLUMINANCE_CLUSTER,-1,""},
	{ILLUMINANCE_CLUSTER,ILLUMINANCE_VAL_ATTRIBUTE,"luxReading"},

	{OCCUPANCY_CLUSTER,-1,""},
	{OCCUPANCY_CLUSTER,OCCUPANCY_VAL_ATTRIBUTE,"occupancyReading"},
	{OCCUPANCY_CLUSTER,OCCUPANCY_SENSOR_TYPE_ATTRIBUTE,"occupancySensorType"},

	{ELECTRICAL_CLUSTER,-1,""},
	{ELECTRICAL_CLUSTER,RMS_VOLTAGE_VAL_ATTRIBUTE,"rmsVoltage"},
	{ELECTRICAL_CLUSTER,RMS_CURRENT_VAL_ATTRIBUTE,"rmsCurrent"},
	{ELECTRICAL_CLUSTER,ACTIVE_POWER_VAL_ATTRIBUTE,"activePower"},
	{ELECTRICAL_CLUSTER,ALARMS_MASK_ATTRIBUTE,"alarmMask"},
	{ELECTRICAL_CLUSTER,VOLTAGE_OVERLOAD_ATTRIBUTE,"voltageOverload"},
	{ELECTRICAL_CLUSTER,CURRENT_OVERLOAD_ATTRIBUTE,"currentOverload"},
	{ELECTRICAL_CLUSTER,ACTIVE_POWER_OVERLOAD_ATTRIBUTE,"powerOverload"},

	{SOIL_NODE_PH_CLUSTER,-1,""},
	{SOIL_NODE_PH_CLUSTER,SOIL_NODE_PH_ATTRIBUTE,"soilPh"},
	{SOIL_NODE_MOISTURE_CLUSTER,-1,""},
	{SOIL_NODE_MOISTURE_CLUSTER,SOIL_NODE_MOISTURE_ATTRIBUTE,"soilMoisture"},

	{LIGHT_SHILED_CLUSTER,-1,""},
	{LIGHT_SHILED_CLUSTER,LIGHT_SHILED_R_ATTRIBUTE,"R"},
	{LIGHT_SHILED_CLUSTER,LIGHT_SHILED_G_ATTRIBUTE,"G"},
	{LIGHT_SHILED_CLUSTER,LIGHT_SHILED_B_ATTRIBUTE,"B"},

	{POWER_CONF_CLUSTER,-1,""},
	{POWER_CONF_CLUSTER,POWER_BATTERY_VOLTAGE_ATTRIBUTE, "batteryVoltage"},

	{SCM_TEMPERATURE_CLUSTER,-1,""},
	{SCM_TEMPERATURE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"temperature"},
	{SCM_PRESSURE_CLUSTER,-1,""},
	{SCM_PRESSURE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"pressure"},
	{SCM_HUMIDITY_CLUSTER,-1,""},
	{SCM_HUMIDITY_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"humidity"},
	{SCM_CARBON_MONOXIDE_CLUSTER,-1,""},
	{SCM_CARBON_MONOXIDE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"carbon_monoxide"},
	{SCM_CARBON_DIOXIDE_CLUSTER,-1,""},
	{SCM_CARBON_DIOXIDE_CLUSTER,SCM_MEASURED_VALUE_ATTRIBUTE,"carbon_dioxide"}
};

typedef struct deviceTypeInfo {
	int deviceTypeId;
	char deviceTypeName[20];
} DEVICETYPE;

/* TODO : Add LED Node and SCM Device info*/
DEVICETYPE deviceTypeArray[] = {
	{DEVICE_TYPE_SOIL_NODE,"SoilNode"},
	{DEVICE_TYPE_LIGHT_SHIELD,"LightShield"},
	{DEVICE_TYPE_CONTACT_SENSOR,"ContactSensor"},
	{DEVICE_ID_DIMMABLE_LIGHT,"LedNode"},
	{DEVICE_TYPE_SCM,"SCMNode"}
};

#endif // __ZIGBEE_ATTRIBUTES_H__
/*
 * End zigbee_attributes.h
 */
