// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BOOTLOADER_CALLBACKS__
#define __BOOTLOADER_CALLBACKS__


#endif // __BOOTLOADER_CALLBACKS__
