<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efr32.efr32bg12p.wtimer0" label="WTIMER0" name="WTIMER0" description="" version="efr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="WTIMER.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="WTIMER.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="WTIMER.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="WTIMER.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="WTIMER.customname.STRING" defaultValue="" hidden="false" readonly="false"/>
    </properties>
    <propertyCategories>
      <category label="WTIMER0">
        <subCategory label="">
          <propertyRef refId="WTIMER.usedbysdk.BOOL"/>
          <propertyRef refId="WTIMER.hiddenbysdk.BOOL"/>
          <propertyRef refId="WTIMER.showadvanced.BOOL"/>
          <propertyRef refId="WTIMER.owner.STRING"/>
          <propertyRef refId="WTIMER.customname.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
