#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_REJOIN_TIME_M    15
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_RETRY_TIME_S     5
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_REJOIN_ATTEMPTS  20

#define TOKEN_FORCE_SHORT_POLL      0
#define TOKEN_FORCE_SHORT_POLL_SIZE 1
