// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __NCP_CONFIG__
#define __NCP_CONFIG__




// Top level macros
#define EMBER_AF_DEVICE_NAME "ncp-uart-sw"


// Generated plugin macros

// Use this macro to check if ADC plugin is included
#define EMBER_AF_PLUGIN_ADC

// Use this macro to check if Antenna Stub plugin is included
#define EMBER_AF_PLUGIN_ANTENNA_STUB

// Use this macro to check if Binding Table Library plugin is included
#define EMBER_AF_PLUGIN_BINDING_TABLE_LIBRARY
// User options for plugin Binding Table Library
#define EMBER_BINDING_TABLE_SIZE 32

// Use this macro to check if Button Stub plugin is included
#define EMBER_AF_PLUGIN_BUTTON_STUB

// Use this macro to check if Buzzer Stub plugin is included
#define EMBER_AF_PLUGIN_BUZZER_STUB

// Use this macro to check if CBKE 163k Stub Library plugin is included
#define EMBER_AF_PLUGIN_CBKE_163K1_STUB_LIBRARY

// Use this macro to check if CBKE 283k Stub Library plugin is included
#define EMBER_AF_PLUGIN_CBKE_283K1_STUB_LIBRARY

// Use this macro to check if CBKE DSA Sign Stub Library plugin is included
#define EMBER_AF_PLUGIN_CBKE_LIBRARY_DSA_SIGN_STUB

// Use this macro to check if CBKE 283k1 DSA Verify Stub Library plugin is included
#define EMBER_AF_PLUGIN_CBKE_LIBRARY_DSA_VERIFY_283K1_STUB

// Use this macro to check if CBKE DSA Verify Stub Library plugin is included
#define EMBER_AF_PLUGIN_CBKE_LIBRARY_DSA_VERIFY_STUB

// Use this macro to check if CBKE Core Stub Library plugin is included
#define EMBER_AF_PLUGIN_CBKE_STUB_LIBRARY

// Use this macro to check if Radio Coexistence plugin is included
#define EMBER_AF_PLUGIN_COEXISTENCE

// Use this macro to check if Concentrator Support Library plugin is included
#define EMBER_AF_PLUGIN_CONCENTRATOR_SUPPORT_LIBRARY

// Use this macro to check if Debug Basic Library plugin is included
#define EMBER_AF_PLUGIN_DEBUG_BASIC_LIBRARY

// Use this macro to check if Debug JTAG plugin is included
#define EMBER_AF_PLUGIN_DEBUG_CHANNEL

// Use this macro to check if Debug Extended Library plugin is included
#define EMBER_AF_PLUGIN_DEBUG_EXTENDED_LIBRARY

// Use this macro to check if Diagnostic plugin is included
#define EMBER_AF_PLUGIN_DIAGNOSTIC

// Use this macro to check if Ember Minimal Printf plugin is included
#define EMBER_AF_PLUGIN_EMBER_MINIMAL_PRINTF

// Use this macro to check if End Device Bind Library plugin is included
#define EMBER_AF_PLUGIN_END_DEVICE_BIND_LIBRARY

// Use this macro to check if External Device GPIO Driver plugin is included
#define EMBER_AF_PLUGIN_EXT_DEVICE

// Use this macro to check if Binding Library EZSP Command Handlers plugin is included
#define EMBER_AF_PLUGIN_EZSP_BINDING

// Use this macro to check if CBKE Library EZSP Command Handlers plugin is included
#define EMBER_AF_PLUGIN_EZSP_CBKE

// Use this macro to check if GP Library EZSP Command Handlers plugin is included
#define EMBER_AF_PLUGIN_EZSP_GP

// Use this macro to check if Manufacturing Library EZSP Command Handlers plugin is included
#define EMBER_AF_PLUGIN_EZSP_MFGLIB

// Use this macro to check if Zigbee PRO Core Security Library EZSP Command Handlers plugin is included
#define EMBER_AF_PLUGIN_EZSP_SECURITY

// Use this macro to check if Zigbee PRO Library EZSP Command Handlers plugin is included
#define EMBER_AF_PLUGIN_EZSP_ZIGBEE_PRO

// Use this macro to check if ZigBee Light Link EZSP Command Handlers plugin is included
#define EMBER_AF_PLUGIN_EZSP_ZLL

// Use this macro to check if GreenPower Stack Library plugin is included
#define EMBER_AF_PLUGIN_GP_LIBRARY

// Use this macro to check if HAL Library plugin is included
#define EMBER_AF_PLUGIN_HAL_LIBRARY

// Use this macro to check if Install Code Library plugin is included
#define EMBER_AF_PLUGIN_INSTALL_CODE_LIBRARY

// Use this macro to check if LED plugin is included
#define EMBER_AF_PLUGIN_LED

// Use this macro to check if Manufacturing Library plugin is included
#define EMBER_AF_PLUGIN_MFGLIB_LIBRARY

// Use this macro to check if Multi-Network Library plugin is included
#define EMBER_AF_PLUGIN_MULTI_NETWORK_LIBRARY
// User options for plugin Multi-Network Library
#define EMBER_SUPPORTED_NETWORKS 2

// Use this macro to check if NCP - UART plugin is included
#define EMBER_AF_PLUGIN_NCP_UART
// User options for plugin NCP - UART
#define EMBER_AF_PLUGIN_NCP_UART_FLOW_CONTROL SOFTWARE

// Use this macro to check if Packet Validate Library plugin is included
#define EMBER_AF_PLUGIN_PACKET_VALIDATE_LIBRARY

// Use this macro to check if RAIL Library plugin is included
#define EMBER_AF_PLUGIN_RAIL_LIBRARY
// User options for plugin RAIL Library
#define EMBER_AF_PLUGIN_RAIL_LIBRARY_RAILPHYDEF 1

// Use this macro to check if Secure EZSP Stub plugin is included
#define EMBER_AF_PLUGIN_SECURE_EZSP_STUB

// Use this macro to check if ZigBee PRO Core Security Library plugin is included
#define EMBER_AF_PLUGIN_SECURITY_LIBRARY_CORE
// User options for plugin ZigBee PRO Core Security Library
#define EMBER_TRANSIENT_KEY_TIMEOUT_S 300

// Use this macro to check if Security Link Keys Library plugin is included
#define EMBER_AF_PLUGIN_SECURITY_LIBRARY_LINK_KEYS
// User options for plugin Security Link Keys Library
#define EMBER_KEY_TABLE_SIZE 12
#define EMBER_REQUEST_KEY_TIMEOUT 0

// Use this macro to check if Serial plugin is included
#define EMBER_AF_PLUGIN_SERIAL

// Use this macro to check if Simulated EEPROM version 2 Library plugin is included
#define EMBER_AF_PLUGIN_SIM_EEPROM2
// User options for plugin Simulated EEPROM version 2 Library
#define EMBER_AF_PLUGIN_SIM_EEPROM2_PASSWORD "!spoon"
#define EMBER_AF_PLUGIN_SIM_EEPROM2_PASSWORD_LENGTH (6)

// Use this macro to check if Simulated EEPROM version 1 to version 2 Upgrade Stub plugin is included
#define EMBER_AF_PLUGIN_SIM_EEPROM2_1TO2_UPGRADE_STUB

// Use this macro to check if XNCP Stub Library plugin is included
#define EMBER_AF_PLUGIN_XNCP_STUB

// Use this macro to check if Zigbee PRO Stack Library plugin is included
#define EMBER_AF_PLUGIN_ZIGBEE_PRO_STACK
// User options for plugin Zigbee PRO Stack Library
#define EMBER_APS_UNICAST_MESSAGE_COUNT 50
#define EMBER_MAX_END_DEVICE_CHILDREN 64
#define EMBER_END_DEVICE_POLL_TIMEOUT_SHIFT 6
#define EMBER_END_DEVICE_POLL_TIMEOUT 5
#define EMBER_LINK_POWER_DELTA_INTERVAL 300
#define EMBER_PACKET_BUFFER_COUNT 64
#define EMBER_SOURCE_ROUTE_TABLE_SIZE 0
#define EMBER_BROADCAST_TABLE_SIZE 15
#define EMBER_NEIGHBOR_TABLE_SIZE 16

// Use this macro to check if Zigbee R22 Support Stub Library plugin is included
#define EMBER_AF_PLUGIN_ZIGBEE_R22_SUPPORT_STUB_LIBRARY

// Use this macro to check if ZigBee Light Link Library plugin is included
#define EMBER_AF_PLUGIN_ZLL_LIBRARY


// Generated API headers

// API adc-cortexm3 from ADC plugin
#define EMBER_AF_API_ADC_CORTEXM3 "../../../platform/base/hal/plugin/adc/adc-cortexm3.h"

// API adc from ADC plugin
#define EMBER_AF_API_ADC "../../../platform/base/hal/plugin/adc/adc.h"

// API antenna from Antenna Stub plugin
#define EMBER_AF_API_ANTENNA "../../../platform/base/hal/plugin/antenna/antenna.h"

// API binding from Binding Table Library plugin
#define EMBER_AF_API_BINDING "../../../protocol/zigbee/stack/include/binding-table.h"

// API button from Button Stub plugin
#define EMBER_AF_API_BUTTON "../../../platform/base/hal/micro/button.h"

// API buzzer from Buzzer Stub plugin
#define EMBER_AF_API_BUZZER "../../../platform/base/hal/plugin/buzzer/buzzer.h"

// API cbke from CBKE Core Stub Library plugin
#define EMBER_AF_API_CBKE "../../../protocol/zigbee/stack/include/cbke-crypto-engine.h"

// API coexistence from Radio Coexistence plugin
#define EMBER_AF_API_COEXISTENCE "../../../platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154/coexistence-802154.h"

// API concentrator-support from Concentrator Support Library plugin
#define EMBER_AF_API_CONCENTRATOR_SUPPORT "../../../protocol/zigbee/app/em260/concentrator.h"

// API debug-basic from Debug Basic Library plugin
#define EMBER_AF_API_DEBUG_BASIC "../../../protocol/zigbee/stack/include/ember-debug.h"

// API diagnostic-cortexm3 from Diagnostic plugin
#define EMBER_AF_API_DIAGNOSTIC_CORTEXM3 "../../../platform/base/hal/micro/cortexm3/diagnostic.h"

// API diagnostic from Diagnostic plugin
#define EMBER_AF_API_DIAGNOSTIC "../../../platform/base/hal/micro/diagnostic.h"

// API ezsp-security from Zigbee PRO Core Security Library EZSP Command Handlers plugin
#define EMBER_AF_API_EZSP_SECURITY "../../../protocol/zigbee/app/em260/command-handlers-security.h"

// API crc from HAL Library plugin
#define EMBER_AF_API_CRC "../../../platform/base/hal/micro/crc.h"

// API endian from HAL Library plugin
#define EMBER_AF_API_ENDIAN "../../../platform/base/hal/micro/endian.h"

// API hal from HAL Library plugin
#define EMBER_AF_API_HAL "../../../platform/base/hal/hal.h"

// API random from HAL Library plugin
#define EMBER_AF_API_RANDOM "../../../platform/base/hal/micro/random.h"

// API system-timer from HAL Library plugin
#define EMBER_AF_API_SYSTEM_TIMER "../../../platform/base/hal/micro/system-timer.h"

// API token-cortexm3 from HAL Library plugin
#define EMBER_AF_API_TOKEN_CORTEXM3 "../../../platform/base/hal/micro/cortexm3/token.h"

// API token from HAL Library plugin
#define EMBER_AF_API_TOKEN "../../../platform/base/hal/micro/token.h"

// API led from LED plugin
#define EMBER_AF_API_LED "../../../platform/base/hal/micro/led.h"

// API mfglib from Manufacturing Library plugin
#define EMBER_AF_API_MFGLIB "../../../protocol/zigbee/stack/include/mfglib.h"

// API multi-network from Multi-Network Library plugin
#define EMBER_AF_API_MULTI_NETWORK "../../../protocol/zigbee/stack/include/multi-network.h"

// API ezsp from NCP - UART plugin
#define EMBER_AF_API_EZSP "../../../protocol/zigbee/app/em260/command-context.h"

// API ezsp-protocol from NCP - UART plugin
#define EMBER_AF_API_EZSP_PROTOCOL "../../../protocol/zigbee/app/util/ezsp/ezsp-protocol.h"

// API rail-library from RAIL Library plugin
#define EMBER_AF_API_RAIL_LIBRARY "../../../platform/radio/rail_lib/common/rail.h"

// API secure-ezsp from Secure EZSP Stub plugin
#define EMBER_AF_API_SECURE_EZSP "../../../protocol/zigbee/app/util/ezsp/secure-ezsp-protocol.h"

// API serial from Serial plugin
#define EMBER_AF_API_SERIAL "../../../platform/base/hal/plugin/serial/serial.h"

// API sim-eeprom from Simulated EEPROM version 2 Library plugin
#define EMBER_AF_API_SIM_EEPROM "../../../platform/base/hal/plugin/sim-eeprom/sim-eeprom.h"

// API zigbee-pro from Zigbee PRO Stack Library plugin
#define EMBER_AF_API_ZIGBEE_PRO "../../../protocol/zigbee/stack/include/ember.h"

// API event from Zigbee PRO Stack Library plugin
#define EMBER_AF_API_EVENT "../../../protocol/zigbee/stack/include/event.h"

// API buffer from Zigbee PRO Stack Library plugin
#define EMBER_AF_API_BUFFER "../../../protocol/zigbee/stack/include/packet-buffer.h"

// API ember-types from Zigbee PRO Stack Library plugin
#define EMBER_AF_API_EMBER_TYPES "../../../protocol/zigbee/stack/include/ember-types.h"

// API byte-utilities from Zigbee PRO Stack Library plugin
#define EMBER_AF_API_BYTE_UTILITIES "../../../protocol/zigbee/stack/include/byte-utilities.h"

// API stack from Zigbee PRO Stack Library plugin
#define EMBER_AF_API_STACK "../../../protocol/zigbee/stack/include/ember.h"

// API zll from ZigBee Light Link Library plugin
#define EMBER_AF_API_ZLL "../../../protocol/zigbee/stack/include/zll-api.h"


// Custom macros
#ifdef EZSP_TOKEN_SIZE
#undef EZSP_TOKEN_SIZE
#endif
#define EZSP_TOKEN_SIZE 8

#ifdef EZSP_TOKEN_ENTRIES
#undef EZSP_TOKEN_ENTRIES
#endif
#define EZSP_TOKEN_ENTRIES 32

#ifdef SOURCE_ROUTE_TABLE_MEMORY
#undef SOURCE_ROUTE_TABLE_MEMORY
#endif
#define SOURCE_ROUTE_TABLE_MEMORY 40

#ifdef BINDING_TABLE_MEMORY
#undef BINDING_TABLE_MEMORY
#endif
#define BINDING_TABLE_MEMORY 60

#ifdef BROADCAST_TABLE_MEMORY
#undef BROADCAST_TABLE_MEMORY
#endif
#define BROADCAST_TABLE_MEMORY (EMBER_BROADCAST_TABLE_SIZE*5)

#ifdef EXTRA_MEMORY
#undef EXTRA_MEMORY
#endif
#define EXTRA_MEMORY (SOURCE_ROUTE_TABLE_MEMORY+BINDING_TABLE_MEMORY+BROADCAST_TABLE_MEMORY)

#ifdef RESERVED_AVAILABLE_MEMORY
#undef RESERVED_AVAILABLE_MEMORY
#endif
#define RESERVED_AVAILABLE_MEMORY (EMBER_PACKET_BUFFER_COUNT+EXTRA_MEMORY)

#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32MG13P632F512GM48

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY M

#ifdef EMBER_AF_RADIO_SERIES
#undef EMBER_AF_RADIO_SERIES
#endif
#define EMBER_AF_RADIO_SERIES 1

#ifdef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#undef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_RADIO_DEVICE_CONFIGURATION 3

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE P

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 632

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 512K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 48

#ifdef EMBER_AF_RADIO_MODULE
#undef EMBER_AF_RADIO_MODULE
#endif
#define EMBER_AF_RADIO_MODULE XX

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32MG13P632F512GM48

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY M

#ifdef EMBER_AF_MCU_SERIES
#undef EMBER_AF_MCU_SERIES
#endif
#define EMBER_AF_MCU_SERIES 1

#ifdef EMBER_AF_MCU_DEVICE_CONFIGURATION
#undef EMBER_AF_MCU_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_MCU_DEVICE_CONFIGURATION 3

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE P

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 632

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 512K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 48

#ifdef EMBER_AF_MCU_MODULE
#undef EMBER_AF_MCU_MODULE
#endif
#define EMBER_AF_MCU_MODULE XX

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4306C



#endif // __NCP_CONFIG__
