// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_EMBER_TYPES
#include EMBER_AF_API_EZSP

// GetValue function declarations.
void emberAfPluginEzspMfglibGetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-mfglib
void emberAfPluginEzspSecurityGetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-security
void emberAfPluginEzspZigbeeProGetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-zigbee-pro
void emberAfPluginEzspGetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ncp-uart

void emberAfEzspGetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context)
{
  emberAfPluginEzspMfglibGetValueCommandCallback(context);  // Plugin: ezsp-mfglib
  emberAfPluginEzspSecurityGetValueCommandCallback(context);  // Plugin: ezsp-security
  emberAfPluginEzspZigbeeProGetValueCommandCallback(context);  // Plugin: ezsp-zigbee-pro
  emberAfPluginEzspGetValueCommandCallback(context);  // Plugin: ncp-uart
}

// GetExtendedValue function declarations.
void emberAfPluginEzspZigbeeProGetExtendedValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-zigbee-pro

void emberAfEzspGetExtendedValueCommandCallback(EmberAfPluginEzspValueCommandContext* context)
{
  emberAfPluginEzspZigbeeProGetExtendedValueCommandCallback(context);  // Plugin: ezsp-zigbee-pro
}

// SetValue function declarations.
void emberAfPluginEzspCbkeSetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-cbke
void emberAfPluginEzspMfglibSetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-mfglib
void emberAfPluginEzspSecuritySetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-security
void emberAfPluginEzspZigbeeProSetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ezsp-zigbee-pro
void emberAfPluginEzspSetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context);  // Plugin: ncp-uart

void emberAfEzspSetValueCommandCallback(EmberAfPluginEzspValueCommandContext* context)
{
  emberAfPluginEzspCbkeSetValueCommandCallback(context);  // Plugin: ezsp-cbke
  emberAfPluginEzspMfglibSetValueCommandCallback(context);  // Plugin: ezsp-mfglib
  emberAfPluginEzspSecuritySetValueCommandCallback(context);  // Plugin: ezsp-security
  emberAfPluginEzspZigbeeProSetValueCommandCallback(context);  // Plugin: ezsp-zigbee-pro
  emberAfPluginEzspSetValueCommandCallback(context);  // Plugin: ncp-uart
}

// GetPolicy function declarations.
void emberAfPluginEzspBindingPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-binding
void emberAfPluginEzspSecurityPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-security
void emberAfPluginEzspZigbeeProPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-zigbee-pro
void emberAfPluginEzspZllPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-zll
void emberAfPluginEzspPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ncp-uart

void emberAfEzspGetPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context)
{
  emberAfPluginEzspBindingPolicyCommandCallback(context);  // Plugin: ezsp-binding
  emberAfPluginEzspSecurityPolicyCommandCallback(context);  // Plugin: ezsp-security
  emberAfPluginEzspZigbeeProPolicyCommandCallback(context);  // Plugin: ezsp-zigbee-pro
  emberAfPluginEzspZllPolicyCommandCallback(context);  // Plugin: ezsp-zll
  emberAfPluginEzspPolicyCommandCallback(context);  // Plugin: ncp-uart
}

// SetPolicy function declarations.
void emberAfPluginEzspBindingPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-binding
void emberAfPluginEzspSecurityPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-security
void emberAfPluginEzspZigbeeProPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-zigbee-pro
void emberAfPluginEzspZllPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ezsp-zll
void emberAfPluginEzspPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context);  // Plugin: ncp-uart

void emberAfEzspSetPolicyCommandCallback(EmberAfPluginEzspPolicyCommandContext* context)
{
  emberAfPluginEzspBindingPolicyCommandCallback(context);  // Plugin: ezsp-binding
  emberAfPluginEzspSecurityPolicyCommandCallback(context);  // Plugin: ezsp-security
  emberAfPluginEzspZigbeeProPolicyCommandCallback(context);  // Plugin: ezsp-zigbee-pro
  emberAfPluginEzspZllPolicyCommandCallback(context);  // Plugin: ezsp-zll
  emberAfPluginEzspPolicyCommandCallback(context);  // Plugin: ncp-uart
}

// GetConfigurationValue function declarations.
void emberAfPluginEzspBindingConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-binding
void emberAfPluginEzspCbkeConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-cbke
void emberAfPluginEzspSecurityGetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-security
void emberAfPluginEzspZigbeeProGetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-zigbee-pro
void emberAfPluginEzspZllConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-zll
void emberAfPluginEzspGetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ncp-uart

void emberAfEzspGetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context)
{
  emberAfPluginEzspBindingConfigurationValueCommandCallback(context);  // Plugin: ezsp-binding
  emberAfPluginEzspCbkeConfigurationValueCommandCallback(context);  // Plugin: ezsp-cbke
  emberAfPluginEzspSecurityGetConfigurationValueCommandCallback(context);  // Plugin: ezsp-security
  emberAfPluginEzspZigbeeProGetConfigurationValueCommandCallback(context);  // Plugin: ezsp-zigbee-pro
  emberAfPluginEzspZllConfigurationValueCommandCallback(context);  // Plugin: ezsp-zll
  emberAfPluginEzspGetConfigurationValueCommandCallback(context);  // Plugin: ncp-uart
}

// SetConfigurationValue function declarations.
void emberAfPluginEzspBindingConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-binding
void emberAfPluginEzspCbkeConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-cbke
void emberAfPluginEzspSecuritySetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-security
void emberAfPluginEzspZigbeeProSetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-zigbee-pro
void emberAfPluginEzspZllConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ezsp-zll
void emberAfPluginEzspSetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context);  // Plugin: ncp-uart

void emberAfEzspSetConfigurationValueCommandCallback(EmberAfPluginEzspConfigurationValueCommandContext* context)
{
  emberAfPluginEzspBindingConfigurationValueCommandCallback(context);  // Plugin: ezsp-binding
  emberAfPluginEzspCbkeConfigurationValueCommandCallback(context);  // Plugin: ezsp-cbke
  emberAfPluginEzspSecuritySetConfigurationValueCommandCallback(context);  // Plugin: ezsp-security
  emberAfPluginEzspZigbeeProSetConfigurationValueCommandCallback(context);  // Plugin: ezsp-zigbee-pro
  emberAfPluginEzspZllConfigurationValueCommandCallback(context);  // Plugin: ezsp-zll
  emberAfPluginEzspSetConfigurationValueCommandCallback(context);  // Plugin: ncp-uart
}

// ModifyMemoryAllocation function declarations.
void emInitializeBindingTable(void);  // Plugin: ezsp-binding
void emberAfPluginEzspZigbeeProModifyMemoryAllocationCallback(void);  // Plugin: ezsp-zigbee-pro

void emberAfPluginEzspModifyMemoryAllocationCallback(void)
{
  emInitializeBindingTable();  // Plugin: ezsp-binding
  emberAfPluginEzspZigbeeProModifyMemoryAllocationCallback();  // Plugin: ezsp-zigbee-pro
}

// PermitHostToNcpFrame function declarations.
void emberAfPluginEzspBindingPermitHostToNcpFrameCallback(bool* permit);  // Plugin: ezsp-binding
void emberAfPluginEzspCbkePermitHostToNcpFrameCallback(bool* permit);  // Plugin: ezsp-cbke

void emberAfPluginEzspPermitHostToNcpFrameCallback(bool* permit)
{
  emberAfPluginEzspBindingPermitHostToNcpFrameCallback(permit);  // Plugin: ezsp-binding
  emberAfPluginEzspCbkePermitHostToNcpFrameCallback(permit);  // Plugin: ezsp-cbke
}

// Init function declarations.
void emberAfMainInitCallback(void);  // Plugin: ncp-uart

void emberAfInit(void)
{
  emberAfMainInitCallback();  // Plugin: ncp-uart
}

// Tick function declarations.
void emberAfMainTickCallback(void);  // Plugin: ncp-uart

void emberAfTick(void)
{
  emberAfMainTickCallback();  // Plugin: ncp-uart
}
