void emberAfPluginDeviceQueryServiceEnableDisable(bool enable);
bool emberAfPluginDeviceQueryServiceGetEnabledState(void);
void emberAfPluginDeviceQueryServiceGetCurrentDiscoveryTargetEui64(EmberEUI64 returnEui64);
