// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BOOTLOADER_CALLBACKS__
#define __BOOTLOADER_CALLBACKS__


#include "config/btl_config.h"
#include "em_gpio.h"


/***************************************************************************//**
 * Custom storage init function.
 *
 * This function can be implemented by the user to perform extra operations
 * during initialization of the storage plugin, such as turning on a GPIO power
 * pin to an external storage medium, toggling a write protect pin, etc.
 * The custom init function is called by @ref storage_init.
 ******************************************************************************/
void storage_customInit(void);

/***************************************************************************//**
 * Custom storage shutdown function.
 *
 * This function can be implemented by the user to perform extra operations
 * during shutdown of the storage plugin, such as turning off a GPIO power
 * pin to an external storage medium.
 * The custom shutdown function is called by @ref storage_shutdown.
 ******************************************************************************/
void storage_customShutdown(void);

#endif // __BOOTLOADER_CALLBACKS__
