// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "af.h"

// Init function declarations.
void emberAfMainInitCallback(void);
void emberAfInit(void);
void emberAfPluginGatewayInitCallback(void);
void emberAfPluginNetworkCreatorSecurityInitCallback(void);

void emAfInit(void)
{
  emberAfMainInitCallback();
  emberAfInit();
  emberAfPluginGatewayInitCallback();
  emberAfPluginNetworkCreatorSecurityInitCallback();
}

// Tick function declarations.
void emberAfMainTickCallback(void);
void emberAfTick(void);
void emberAfPluginGatewayTickCallback(void);
void emberAfPluginHeartbeatTickCallback(void);
void emberAfOtaServerTick(void);

void emAfTick(void)
{
  emberAfMainTickCallback();
  emberAfTick();
  emberAfPluginGatewayTickCallback();
  emberAfPluginHeartbeatTickCallback();
  emberAfOtaServerTick();
}

void emAfResetAttributes(uint8_t endpointId)
{
}

// PreCommandReceived function declarations.
bool emberAfPreCommandReceivedCallback(EmberAfClusterCommand* cmd);
bool emAfPluginCommandRelayPreCommandReceivedCallback(EmberAfClusterCommand* cmd);
bool emAfPluginDeviceTablePreCommandReceivedCallback(EmberAfClusterCommand* cmd);
bool emberAfPluginGatewayRelayMqttPreCommandReceivedCallback(EmberAfClusterCommand* cmd);

bool emAfPreCommandReceived(EmberAfClusterCommand* cmd)
{
  return (emberAfPreCommandReceivedCallback(cmd)
          || emAfPluginCommandRelayPreCommandReceivedCallback(cmd)
          || emAfPluginDeviceTablePreCommandReceivedCallback(cmd)
          || emberAfPluginGatewayRelayMqttPreCommandReceivedCallback(cmd));
}

// PreZDOMessageReceived function declarations.
bool emberAfPreZDOMessageReceivedCallback(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);
bool emAfPluginDeviceTablePreZDOMessageReceived(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);
bool emberAfPluginGatewayRelayMqttPreZDOMessageReceivedCallback(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);

bool emAfPreZDOMessageReceived(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length)
{
  return (emberAfPreZDOMessageReceivedCallback(emberNodeId, apsFrame, message, length)
          || emAfPluginDeviceTablePreZDOMessageReceived(emberNodeId, apsFrame, message, length)
          || emberAfPluginGatewayRelayMqttPreZDOMessageReceivedCallback(emberNodeId, apsFrame, message, length));
}

// RetrieveAttributeAndCraftResponse function declarations.
bool emAfPluginGreenPowerClientRetrieveAttributeAndCraftResponse(uint8_t endpoint, EmberAfClusterId clusterId, EmberAfAttributeId attrId, uint8_t mask, uint16_t maunfacturerCode, uint16_t readLength);

bool emAfRetrieveAttributeAndCraftResponse(uint8_t endpoint, EmberAfClusterId clusterId, EmberAfAttributeId attrId, uint8_t mask, uint16_t maunfacturerCode, uint16_t readLength)
{
  return emAfPluginGreenPowerClientRetrieveAttributeAndCraftResponse(endpoint, clusterId, attrId, mask, maunfacturerCode, readLength);
}

// ZigbeeKeyEstablishment function declarations.
void emberAfZigbeeKeyEstablishmentCallback(EmberEUI64 partner, EmberKeyStatus status);
void emberAfPluginNetworkCreatorSecurityZigbeeKeyEstablishmentCallback(EmberEUI64 partner, EmberKeyStatus status);

void emAfZigbeeKeyEstablishment(EmberEUI64 partner, EmberKeyStatus status)
{
  emberAfZigbeeKeyEstablishmentCallback(partner, status);
  emberAfPluginNetworkCreatorSecurityZigbeeKeyEstablishmentCallback(partner, status);
}

// ReadAttributesResponse function declarations.
bool emberAfReadAttributesResponseCallback(EmberAfClusterId clusterId,uint8_t* buffer,uint16_t bufLen);

bool emAfReadAttributesResponse(EmberAfClusterId clusterId,uint8_t* buffer,uint16_t bufLen)
{
  return emberAfReadAttributesResponseCallback(clusterId, buffer, bufLen);
}

// ReportAttributes function declarations.
bool emberAfReportAttributesCallback(EmberAfClusterId clusterId,uint8_t * buffer,uint16_t bufLen);

bool emAfReportAttributes(EmberAfClusterId clusterId,uint8_t * buffer,uint16_t bufLen)
{
  return emberAfReportAttributesCallback(clusterId, buffer, bufLen);
}

// PluginDeviceTableDeviceLeft function declarations.
void emberAfPluginDeviceTableDeviceLeftCallback(EmberEUI64 newNodeEui64);
void emAfPluginCommandRelayRemoveDeviceByEui64(EmberEUI64 newNodeEui64);

void emAfPluginDeviceTableDeviceLeftCallback(EmberEUI64 newNodeEui64)
{
  emberAfPluginDeviceTableDeviceLeftCallback(newNodeEui64);
  emAfPluginCommandRelayRemoveDeviceByEui64(newNodeEui64);
}
